"""API key hashing and verification.

API keys are high-entropy random tokens generated by manage_sources.py (32
bytes of randomness, ~43 base64 characters), not human-chosen passwords. For
that reason we use a plain SHA-256 digest rather than bcrypt/argon2: those
algorithms are deliberately slow to defend against dictionary/brute-force
guessing of *low-entropy* secrets, which does not apply here, and a fast hash
lets the ingestion endpoint stay cheap under load. The digest is compared
with a constant-time comparison to avoid timing side channels.

If a future requirement calls for storing low-entropy, human-chosen
credentials, use bcrypt/argon2 there instead.
"""

import hashlib
import hmac
import secrets


def generate_api_key() -> str:
    return "bkt_" + secrets.token_urlsafe(32)


def hash_api_key(plaintext: str) -> str:
    return hashlib.sha256(plaintext.encode("utf-8")).hexdigest()


def verify_api_key(plaintext: str, hashed: str) -> bool:
    return hmac.compare_digest(hash_api_key(plaintext), hashed)
